services:
  database:
    container_name: w-database
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgsql:/var/lib/postgresql/data
  php:
    container_name: w-php
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
    depends_on:
      - database
  nginx:
    container_name: w-nginx
    image: nginx:stable-alpine
    ports:
      - '8081:81'
    volumes:
      - ./public:/var/www/public
      - ./nginx/nginx-default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - database

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  pgsql:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
